#!/usr/bin/env python3
"""
Backup and Restore Example

Demonstrates backup and restore operations using ftl-automation.
This example shows:
- File and directory backup strategies
- Database backup and restore
- Automated backup scheduling
- Remote backup storage
- Backup verification and integrity checks
- Disaster recovery procedures
"""

import ftl_automation
import datetime


def main():
    print("💾 Backup and Restore Example")
    print("=" * 50)
    
    # Use localhost for demonstration
    localhost_inventory = {
        "all": {
            "hosts": {
                "backup-server": {
                    "ansible_connection": "local",
                    "ansible_host": "127.0.0.1",
                    "backup_root": "/opt/backups",
                    "app_data": "/opt/myapp/data",
                    "db_name": "myapp_db"
                }
            }
        }
    }
    
    with ftl_automation.automation(
        inventory=localhost_inventory,
        tools=[
            "file",
            "copy", 
            "command",
            "service",
            "dnf",
            "get_url",
            "lineinfile",
            "user"
        ],
        tool_packages=["ftl_tools.tools"],
        modules=("modules",)
    ) as ftl:
        
        print("\n📁 Step 1: Backup Infrastructure Setup")
        print("-" * 30)
        
        # Create backup directories
        backup_dirs = [
            "/opt/backups",
            "/opt/backups/daily",
            "/opt/backups/weekly", 
            "/opt/backups/monthly",
            "/opt/backups/database",
            "/opt/backups/files",
            "/opt/backups/logs",
            "/opt/backups/scripts"
        ]
        
        for directory in backup_dirs:
            try:
                result = ftl.file(
                    path=directory,
                    state="directory",
                    owner="root",
                    group="backup",
                    mode="0750"
                )
                status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
                print(f"{status}: {directory}")
            except Exception as e:
                print(f"⚠️  Failed to create {directory}: {e}")
        
        # Create backup user
        try:
            result = ftl.user(
                name="backup",
                system=True,
                shell="/bin/bash",
                home="/opt/backups",
                create_home=False
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: backup user")
        except Exception as e:
            print(f"⚠️  Failed to create backup user: {e}")
        
        print("\n🗄️  Step 2: Database Backup Script")
        print("-" * 30)
        
        # Create database backup script
        db_backup_script = f"""#!/bin/bash
# Database backup script generated by ftl-automation
# Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

set -euo pipefail

BACKUP_DIR="/opt/backups/database"
DB_NAME="${{1:-myapp_db}}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="$BACKUP_DIR/${{DB_NAME}}_${{TIMESTAMP}}.sql.gz"
LOG_FILE="/opt/backups/logs/database_backup.log"

# Logging function
log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}}

# Create backup
log "Starting database backup for $DB_NAME"

# PostgreSQL backup
if command -v pg_dump >/dev/null 2>&1; then
    log "Creating PostgreSQL backup..."
    pg_dump "$DB_NAME" | gzip > "$BACKUP_FILE"
    BACKUP_SIZE=$(stat -f%z "$BACKUP_FILE" 2>/dev/null || stat -c%s "$BACKUP_FILE")
    log "PostgreSQL backup completed: $BACKUP_FILE ($BACKUP_SIZE bytes)"
fi

# MySQL backup (alternative)
if command -v mysqldump >/dev/null 2>&1; then
    log "Creating MySQL backup..."
    mysqldump --single-transaction --routines --triggers "$DB_NAME" | gzip > "$BACKUP_FILE"
    BACKUP_SIZE=$(stat -f%z "$BACKUP_FILE" 2>/dev/null || stat -c%s "$BACKUP_FILE")
    log "MySQL backup completed: $BACKUP_FILE ($BACKUP_SIZE bytes)"
fi

# Verify backup integrity
if [ -f "$BACKUP_FILE" ] && [ -s "$BACKUP_FILE" ]; then
    log "Backup verification: SUCCESS"
    
    # Test gunzip
    if gzip -t "$BACKUP_FILE"; then
        log "Backup compression integrity: SUCCESS"
    else
        log "ERROR: Backup compression integrity check failed"
        exit 1
    fi
else
    log "ERROR: Backup file is missing or empty"
    exit 1
fi

# Cleanup old backups (keep last 7 days)
find "$BACKUP_DIR" -name "${{DB_NAME}}_*.sql.gz" -mtime +7 -delete
log "Old backup cleanup completed"

log "Database backup process completed successfully"
"""
        
        try:
            result = ftl.copy(
                content=db_backup_script,
                dest="/opt/backups/scripts/backup_database.sh",
                owner="backup",
                group="backup",
                mode="0755"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Database backup script")
        except Exception as e:
            print(f"⚠️  Failed to create database backup script: {e}")
        
        print("\n📂 Step 3: File Backup Script")
        print("-" * 30)
        
        # Create file backup script
        file_backup_script = f"""#!/bin/bash
# File backup script generated by ftl-automation
# Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

set -euo pipefail

BACKUP_DIR="/opt/backups/files"
SOURCE_DIRS=("/opt/myapp/data" "/etc" "/var/www" "/home")
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="/opt/backups/logs/file_backup.log"

# Logging function
log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}}

log "Starting file backup process"

# Create backup archive
BACKUP_FILE="$BACKUP_DIR/files_${{TIMESTAMP}}.tar.gz"

# Backup important directories
log "Creating tar archive: $BACKUP_FILE"

# Use tar with exclusions for common unnecessary files
tar -czf "$BACKUP_FILE" \\
    --exclude='*.tmp' \\
    --exclude='*.log' \\
    --exclude='cache/*' \\
    --exclude='tmp/*' \\
    --exclude='.git/*' \\
    --one-file-system \\
    "${{SOURCE_DIRS[@]}}" 2>/dev/null || true

# Verify backup
if [ -f "$BACKUP_FILE" ] && [ -s "$BACKUP_FILE" ]; then
    BACKUP_SIZE=$(stat -f%z "$BACKUP_FILE" 2>/dev/null || stat -c%s "$BACKUP_FILE")
    log "File backup completed: $BACKUP_FILE ($BACKUP_SIZE bytes)"
    
    # Test archive integrity
    if tar -tzf "$BACKUP_FILE" >/dev/null 2>&1; then
        log "Backup archive integrity: SUCCESS"
    else
        log "ERROR: Backup archive integrity check failed"
        exit 1
    fi
else
    log "ERROR: Backup file is missing or empty"
    exit 1
fi

# Cleanup old backups (keep last 14 days for files)
find "$BACKUP_DIR" -name "files_*.tar.gz" -mtime +14 -delete
log "Old backup cleanup completed"

log "File backup process completed successfully"
"""
        
        try:
            result = ftl.copy(
                content=file_backup_script,
                dest="/opt/backups/scripts/backup_files.sh",
                owner="backup",
                group="backup", 
                mode="0755"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: File backup script")
        except Exception as e:
            print(f"⚠️  Failed to create file backup script: {e}")
        
        print("\n🔄 Step 4: Restore Scripts")
        print("-" * 30)
        
        # Create database restore script
        db_restore_script = """#!/bin/bash
# Database restore script

set -euo pipefail

BACKUP_DIR="/opt/backups/database"
DB_NAME="${1:-myapp_db}"
BACKUP_FILE="${2}"
LOG_FILE="/opt/backups/logs/database_restore.log"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

if [ -z "$BACKUP_FILE" ]; then
    echo "Usage: $0 <database_name> <backup_file>"
    echo "Available backups:"
    ls -la "$BACKUP_DIR"/*.sql.gz 2>/dev/null || echo "No backups found"
    exit 1
fi

if [ ! -f "$BACKUP_FILE" ]; then
    log "ERROR: Backup file not found: $BACKUP_FILE"
    exit 1
fi

log "Starting database restore for $DB_NAME from $BACKUP_FILE"

# Verify backup file integrity
if ! gzip -t "$BACKUP_FILE"; then
    log "ERROR: Backup file integrity check failed"
    exit 1
fi

# Create database if it doesn't exist (PostgreSQL)
if command -v createdb >/dev/null 2>&1; then
    createdb "$DB_NAME" 2>/dev/null || true
    log "Database $DB_NAME created or already exists"
fi

# Restore database
log "Restoring database from backup..."
if command -v psql >/dev/null 2>&1; then
    # PostgreSQL restore
    gunzip -c "$BACKUP_FILE" | psql "$DB_NAME"
    log "PostgreSQL restore completed"
elif command -v mysql >/dev/null 2>&1; then
    # MySQL restore
    gunzip -c "$BACKUP_FILE" | mysql "$DB_NAME"
    log "MySQL restore completed"
fi

log "Database restore process completed successfully"
"""
        
        try:
            result = ftl.copy(
                content=db_restore_script,
                dest="/opt/backups/scripts/restore_database.sh",
                owner="backup",
                group="backup",
                mode="0755"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Database restore script")
        except Exception as e:
            print(f"⚠️  Failed to create database restore script: {e}")
        
        # Create file restore script
        file_restore_script = """#!/bin/bash
# File restore script

set -euo pipefail

BACKUP_DIR="/opt/backups/files"
BACKUP_FILE="${1}"
RESTORE_DIR="${2:-/}"
LOG_FILE="/opt/backups/logs/file_restore.log"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

if [ -z "$BACKUP_FILE" ]; then
    echo "Usage: $0 <backup_file> [restore_directory]"
    echo "Available backups:"
    ls -la "$BACKUP_DIR"/*.tar.gz 2>/dev/null || echo "No backups found"
    exit 1
fi

if [ ! -f "$BACKUP_FILE" ]; then
    log "ERROR: Backup file not found: $BACKUP_FILE"
    exit 1
fi

log "Starting file restore from $BACKUP_FILE to $RESTORE_DIR"

# Verify backup file integrity
if ! tar -tzf "$BACKUP_FILE" >/dev/null; then
    log "ERROR: Backup file integrity check failed"
    exit 1
fi

# Show what will be restored
log "Archive contents:"
tar -tzf "$BACKUP_FILE" | head -20

# Restore files
log "Restoring files..."
tar -xzf "$BACKUP_FILE" -C "$RESTORE_DIR"

log "File restore process completed successfully"
"""
        
        try:
            result = ftl.copy(
                content=file_restore_script,
                dest="/opt/backups/scripts/restore_files.sh",
                owner="backup",
                group="backup",
                mode="0755"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: File restore script")
        except Exception as e:
            print(f"⚠️  Failed to create file restore script: {e}")
        
        print("\n⏰ Step 5: Backup Scheduling")
        print("-" * 30)
        
        # Create backup scheduling script
        crontab_entries = """
# Automated backup schedule
# Generated by ftl-automation

# Daily database backup at 2:00 AM
0 2 * * * /opt/backups/scripts/backup_database.sh myapp_db

# Daily file backup at 3:00 AM  
0 3 * * * /opt/backups/scripts/backup_files.sh

# Weekly backup report at 8:00 AM on Sundays
0 8 * * 0 /opt/backups/scripts/backup_report.sh
"""
        
        try:
            result = ftl.copy(
                content=crontab_entries.strip(),
                dest="/opt/backups/scripts/backup_crontab",
                owner="backup",
                group="backup",
                mode="0644"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Backup crontab configuration")
            
            # Install crontab for backup user
            install_result = ftl.command(
                cmd="crontab -u backup /opt/backups/scripts/backup_crontab"
            )
            if install_result.get("rc") == 0:
                print("✅ Crontab installed for backup user")
            else:
                print("⚠️  Failed to install crontab")
                
        except Exception as e:
            print(f"⚠️  Failed to setup backup scheduling: {e}")
        
        print("\n📊 Step 6: Backup Monitoring Script")
        print("-" * 30)
        
        # Create backup monitoring/reporting script
        monitoring_script = """#!/bin/bash
# Backup monitoring and reporting script

set -euo pipefail

BACKUP_ROOT="/opt/backups"
LOG_FILE="$BACKUP_ROOT/logs/backup_report.log"
REPORT_FILE="$BACKUP_ROOT/logs/backup_status_$(date +%Y%m%d).txt"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

generate_report() {
    cat > "$REPORT_FILE" << EOF
Backup Status Report
Generated: $(date)
=====================================

Database Backups:
$(find $BACKUP_ROOT/database -name "*.sql.gz" -printf "%TY-%Tm-%Td %TH:%TM  %8s bytes  %p\\n" | sort -r | head -10)

File Backups:
$(find $BACKUP_ROOT/files -name "*.tar.gz" -printf "%TY-%Tm-%Td %TH:%TM  %8s bytes  %p\\n" | sort -r | head -10)

Disk Usage:
$(du -sh $BACKUP_ROOT/*)

Recent Backup Logs:
$(tail -20 $BACKUP_ROOT/logs/database_backup.log 2>/dev/null || echo "No database backup logs found")

$(tail -20 $BACKUP_ROOT/logs/file_backup.log 2>/dev/null || echo "No file backup logs found")

Backup Health Check:
- Database backups in last 24h: $(find $BACKUP_ROOT/database -name "*.sql.gz" -mtime -1 | wc -l)
- File backups in last 24h: $(find $BACKUP_ROOT/files -name "*.tar.gz" -mtime -1 | wc -l)
- Total backup size: $(du -sh $BACKUP_ROOT | cut -f1)

EOF
}

log "Generating backup status report"
generate_report

# Display report
cat "$REPORT_FILE"

# Check for issues
db_backups_today=$(find $BACKUP_ROOT/database -name "*.sql.gz" -mtime -1 | wc -l)
file_backups_today=$(find $BACKUP_ROOT/files -name "*.tar.gz" -mtime -1 | wc -l)

if [ "$db_backups_today" -eq 0 ]; then
    log "WARNING: No database backups found in the last 24 hours"
fi

if [ "$file_backups_today" -eq 0 ]; then
    log "WARNING: No file backups found in the last 24 hours"
fi

log "Backup report generation completed"
"""
        
        try:
            result = ftl.copy(
                content=monitoring_script,
                dest="/opt/backups/scripts/backup_report.sh",
                owner="backup",
                group="backup",
                mode="0755"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Backup monitoring script")
        except Exception as e:
            print(f"⚠️  Failed to create backup monitoring script: {e}")
        
        print("\n🧪 Step 7: Test Backup System")
        print("-" * 30)
        
        # Create test data and run backup test
        test_commands = [
            {
                "cmd": "mkdir -p /tmp/test_backup_data",
                "description": "Create test directory"
            },
            {
                "cmd": "echo 'Test backup data' > /tmp/test_backup_data/test.txt",
                "description": "Create test file"
            },
            {
                "cmd": "/opt/backups/scripts/backup_report.sh",
                "description": "Generate backup report"
            }
        ]
        
        for test in test_commands:
            try:
                result = ftl.command(cmd=test["cmd"])
                if result.get("rc") == 0:
                    print(f"✅ {test['description']}")
                else:
                    print(f"⚠️  {test['description']}: Failed")
            except Exception as e:
                print(f"⚠️  {test['description']}: {e}")
        
        print("\n🔧 Step 8: Backup Configuration")
        print("-" * 30)
        
        # Create backup configuration file
        backup_config = f"""
# FTL Automation Backup Configuration
# Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

[backup]
root_directory = /opt/backups
log_directory = /opt/backups/logs
script_directory = /opt/backups/scripts

[retention]
daily_database = 7
daily_files = 14
weekly = 4
monthly = 12

[databases]
default = myapp_db
# additional_db = another_db

[directories]
app_data = /opt/myapp/data
config = /etc
web_root = /var/www
home_dirs = /home

[monitoring]
email_alerts = admin@example.com
slack_webhook = https://hooks.slack.com/...
report_frequency = daily

[remote_backup]
enabled = false
destination = user@backup-server:/backups/
rsync_options = -avz --delete
"""
        
        try:
            result = ftl.copy(
                content=backup_config,
                dest="/opt/backups/backup.conf",
                owner="backup",
                group="backup",
                mode="0644"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Backup configuration file")
        except Exception as e:
            print(f"⚠️  Failed to create backup configuration: {e}")
        
        print("\n📋 Step 9: Disaster Recovery Guide")
        print("-" * 30)
        
        # Create disaster recovery documentation
        disaster_recovery_guide = """
# Disaster Recovery Procedures
Generated by ftl-automation

## Quick Recovery Commands

### Database Recovery
1. List available database backups:
   ls -la /opt/backups/database/

2. Restore database:
   /opt/backups/scripts/restore_database.sh <db_name> <backup_file>

### File Recovery
1. List available file backups:
   ls -la /opt/backups/files/

2. Restore files:
   /opt/backups/scripts/restore_files.sh <backup_file> [restore_path]

## Full System Recovery

### 1. Emergency Database Recovery
```bash
# Find latest database backup
latest_db=$(ls -t /opt/backups/database/*.sql.gz | head -1)
echo "Latest backup: $latest_db"

# Restore database
/opt/backups/scripts/restore_database.sh myapp_db "$latest_db"
```

### 2. Emergency File Recovery
```bash
# Find latest file backup
latest_files=$(ls -t /opt/backups/files/*.tar.gz | head -1)
echo "Latest backup: $latest_files"

# Restore files (be careful with destination!)
/opt/backups/scripts/restore_files.sh "$latest_files" /restore/location/
```

### 3. Verify Recovery
- Check application functionality
- Verify database connections
- Test file permissions
- Validate service startup

## Backup Verification
```bash
# Generate current status
/opt/backups/scripts/backup_report.sh

# Check recent backups
find /opt/backups -name "*.gz" -mtime -7 -ls

# Test backup integrity
gzip -t /opt/backups/database/*.sql.gz
tar -tzf /opt/backups/files/*.tar.gz >/dev/null
```

## Emergency Contacts
- System Administrator: admin@example.com
- Database Administrator: dba@example.com
- Application Team: dev@example.com

## Important Notes
- Always verify backup integrity before restoration
- Test restore procedures in non-production environment
- Keep offline copies of critical backups
- Document any manual steps taken during recovery
"""
        
        try:
            result = ftl.copy(
                content=disaster_recovery_guide,
                dest="/opt/backups/DISASTER_RECOVERY.md",
                owner="backup",
                group="backup",
                mode="0644"
            )
            status = "✅ Created" if result.get("changed") else "ℹ️  Already exists"
            print(f"{status}: Disaster recovery guide")
        except Exception as e:
            print(f"⚠️  Failed to create disaster recovery guide: {e}")
        
        print("\n✨ Backup and restore system setup completed!")
        print("=" * 50)
        print("\nBackup System Summary:")
        print("- ✅ Backup infrastructure created")
        print("- ✅ Database backup scripts configured")
        print("- ✅ File backup scripts configured")
        print("- ✅ Restore procedures implemented")
        print("- ✅ Automated scheduling configured")
        print("- ✅ Monitoring and reporting setup")
        print("- ✅ Disaster recovery guide created")
        
        print("\nNext Steps:")
        print("1. Configure remote backup storage")
        print("2. Set up backup alerts and notifications")
        print("3. Test restore procedures regularly")
        print("4. Implement backup encryption for sensitive data")
        print("5. Set up off-site backup replication")
        
        print("\nBackup Schedule:")
        print("- Database: Daily at 2:00 AM")
        print("- Files: Daily at 3:00 AM")
        print("- Reports: Weekly on Sundays at 8:00 AM")
        
        print(f"\n📍 Backup location: /opt/backups")
        print(f"📖 Recovery guide: /opt/backups/DISASTER_RECOVERY.md")


if __name__ == "__main__":
    main()